### ISSUE TITLE
Does not work on OS X 10.6.6

### ISSUE THREAD

**Issue by swmaster** [libretro/bsnes-libretro-cplusplus98#1]
Errors when compiling on recent OS X build:

System Software Overview:

  System Version:   Mac OS X 10.6.6 (10J567)
  Kernel Version:   Darwin 10.6.0
  Boot Volume:  Macintosh HD
  Boot Mode:    Normal
  Computer Name:    <redacted>
  User Name:    <redacted>
  Secure Virtual Memory:    Not Enabled
  64-bit Kernel and Extensions: No
  Time since boot:  1:08

Compile attempt fails:
$ make library profile=compatibility
cc -O3 -fomit-frame-pointer -I. -Isnes -fPIC -DPROFILE_COMPATIBILITY -c libco/libco.c -o obj/libco.o
In file included from libco/libco.c:10:
libco/amd64.c:11:20: error: malloc.h: No such file or directory
make: **\* [obj/libco.o] Error 1

A couple of issues...
Why is it trying to compile amd64.c? I don't have an x86_64 operating system. Is there an issue detecting arch? uname gives "Darwin"

If we really need malloc.h, it should be malloc/malloc.h
